#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
音乐数据扩充脚本
功能：从本地 song 目录选择一个音频文件，上传到 MinIO 并复制多份，
     使用真实歌名和歌手信息创建数据库记录，快速扩充数据量。

用法：
  1. 确保 MySQL 和 MinIO 服务正在运行
  2. pip install pymysql minio
  3. python generate_test_data.py

配置：修改下面的数据库和 MinIO 连接信息
"""

import pymysql
from minio import Minio
from minio.error import S3Error
import os
import sys
import uuid
import random
import datetime
import io
import hashlib

# ============================================================
# 配置信息（与 application-dev.properties 保持一致）
# ============================================================
MYSQL_CONFIG = {
    "host": "localhost",
    "port": 3306,
    "user": "root",
    "password": "root",
    "database": "tp_music",
    "charset": "utf8mb4",
}

MINIO_CONFIG = {
    "endpoint": "localhost:9005",
    "access_key": "root",
    "secret_key": "12345678",
    "bucket_name": "user01",
    "secure": False,
}

# 本地音频文件目录（相对于脚本所在目录的上级 song 目录）
LOCAL_SONG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "song")

# 要生成的数据条数
TARGET_COUNT = 2000

# 是否在 MinIO 中实际复制音频文件（True=复制, False=复用同一个文件）
COPY_AUDIO_IN_MINIO = False  # 推荐 False，节省 MinIO 存储空间


# ============================================================
# 歌曲数据（从网络搜索整理的真实歌名和歌手）
# 来源：腾讯音乐榜、耳帝年度100佳、Billboard Hot 100、Melon K-pop榜、
#        经典老歌500首等
# ============================================================
SONGS = [
    # ==================== 经典华语老歌 (1-517) ====================
    ("朋友", "周华健"),
    ("最浪漫的事", "赵咏华"),
    ("你怎么舍得我难过", "黄品源"),
    ("大海", "张雨生"),
    ("飘雪", "陈慧娴"),
    ("舞女泪", "韩宝仪"),
    ("一剪梅", "张明敏"),
    ("涛声依旧", "毛宁"),
    ("晚秋", "毛宁"),
    ("一千个伤心的理由", "张学友"),
    ("爱江山更爱美人", "李丽芬"),
    ("吻别", "张学友"),
    ("宝贝对不起", "草蜢"),
    ("再回首", "姜育恒"),
    ("相思风雨中", "张学友"),
    ("上海滩", "叶丽仪"),
    ("梁祝", "吴奇隆"),
    ("朋友别哭", "吕方"),
    ("同桌的你", "老狼"),
    ("爱", "小虎队"),
    ("美酒加咖啡", "邓丽君"),
    ("为爱痴狂", "刘若英"),
    ("感恩的心", "欧阳菲菲"),
    ("大约在冬季", "齐秦"),
    ("童年", "罗大佑"),
    ("懂你", "满文军"),
    ("用心良苦", "张宇"),
    ("心雨", "高胜美"),
    ("风中有朵雨做的云", "孟庭苇"),
    ("喜欢你", "Beyond"),
    ("知心爱人", "付笛生"),
    ("水手", "郑智化"),
    ("小城故事", "邓丽君"),
    ("我想有个家", "潘美辰"),
    ("阳光总在风雨后", "许美静"),
    ("来生缘", "刘德华"),
    ("偏偏喜欢你", "陈百强"),
    ("万水千山总是情", "汪明荃"),
    ("青青河边草", "高胜美"),
    ("铁血丹心", "罗文"),
    ("一生何求", "陈百强"),
    ("爱如潮水", "张信哲"),
    ("花心", "周华健"),
    ("忘情水", "刘德华"),
    ("两忘烟水里", "关正杰"),
    ("路边的野花不要采", "邓丽君"),
    ("昨夜星辰", "龙飘飘"),
    ("萍聚", "李翊君"),
    ("真心英雄", "周华健"),
    ("潇洒走一回", "叶倩文"),
    ("一帘幽梦", "许茹芸"),
    ("一路上有你", "张学友"),
    ("窗外", "李琛"),
    ("红蜻蜓", "小虎队"),
    ("没有情人的情人节", "孟庭苇"),
    ("外婆的澎湖湾", "潘安邦"),
    ("明天你是否依然爱我", "童安格"),
    ("九百九十九朵玫瑰", "邰正宵"),
    ("容易受伤的女人", "王菲"),
    ("其实不想走", "周华健"),
    ("恰似你的温柔", "蔡琴"),
    ("何日君再来", "邓丽君"),
    ("雨一直下", "张宇"),
    ("精忠报国", "屠洪刚"),
    ("千纸鹤", "邰正宵"),
    ("蝴蝶飞呀", "小虎队"),
    ("新鸳鸯蝴蝶梦", "黄安"),
    ("让我欢喜让我忧", "周华健"),
    ("一生爱你千百回", "梅艳芳"),
    ("爱就一个字", "张信哲"),
    ("祝福", "张学友"),
    ("孤枕难眠", "周华健"),
    ("一场游戏一场梦", "王杰"),
    ("我的未来不是梦", "张雨生"),
    ("梦醒时分", "陈淑桦"),
    ("冬季到台北来看雨", "孟庭苇"),
    ("踏浪", "徐怀钰"),
    ("漫步人生路", "邓丽君"),
    ("霸王别姬", "屠洪刚"),
    ("心太软", "任贤齐"),
    ("沧海一声笑", "许冠杰"),
    ("你的样子", "罗大佑"),
    ("恋曲1990", "罗大佑"),
    ("祝你一路顺风", "吴奇隆"),
    ("橄榄树", "齐豫"),
    ("把根留住", "童安格"),
    ("在水一方", "邓丽君"),
    ("等你等到我心痛", "张学友"),
    ("爱我的人和我爱的人", "裘海正"),
    ("沉默是金", "张国荣"),
    ("少年壮志不言愁", "刘欢"),
    ("刀剑如梦", "周华健"),
    ("你究竟有几个好妹妹", "孟庭苇"),
    ("跟往事干杯", "姜育恒"),
    ("棋子", "王菲"),
    ("其实你不懂我的心", "童安格"),
    ("明天会更好", "罗大佑"),
    ("味道", "辛晓琪"),
    ("独上西楼", "邓丽君"),
    ("糊涂的爱", "王志文"),
    ("不让我的眼泪陪我过夜", "齐秦"),
    ("别怕我伤心", "张信哲"),
    ("男人哭吧不是罪", "刘德华"),
    ("你在他乡还好吗", "李进"),
    ("世上只有妈妈好", "毛阿敏"),
    ("你的眼睛背叛你的心", "郑中基"),
    ("一笑而过", "那英"),
    ("把悲伤留给自己", "陈升"),
    ("流浪歌", "陈星"),
    ("再回到从前", "张镐哲"),
    ("千年等一回", "高胜美"),
    ("山不转水转", "那英"),
    ("但愿人长久", "王菲"),
    ("我曾用心爱着你", "潘美辰"),
    ("饿狼传说", "张学友"),
    ("开心的马骝", "刘德华"),
    ("故乡的云", "费翔"),
    ("我是一只小小鸟", "赵传"),
    ("忘忧草", "周华健"),
    ("彩云伴海鸥", "高胜美"),
    ("有一点动心", "张信哲"),
    ("追梦人", "凤飞飞"),
    ("万里长城永不倒", "罗文"),
    ("弯弯的月亮", "刘欢"),
    ("雾里看花", "那英"),
    ("白月光", "张信哲"),
    ("如果这都不算爱", "张学友"),
    ("执着", "田震"),
    ("凡人歌", "李宗盛"),
    ("至少还有你", "林忆莲"),
    ("三月里的小雨", "刘文正"),
    ("滚滚红尘", "陈淑桦"),
    ("星星点灯", "郑智化"),
    ("我是不是该安静的走开", "郭富城"),
    ("哭砂", "黄莺莺"),
    ("你好毒", "张学友"),
    ("笑看风云", "郑少秋"),
    ("谢谢你的爱", "刘德华"),
    ("爱拼才会赢", "叶启田"),
    ("讲不出再见", "谭咏麟"),
    ("归来吧", "陈慧娴"),
    ("当爱已成往事", "张国荣"),
    ("夜来香", "邓丽君"),
    ("人生何处不相逢", "陈慧娴"),
    ("大地", "Beyond"),
    ("分手总要在雨天", "张学友"),
    ("爱相随", "周华健"),
    ("爱你在心口难开", "高胜美"),
    ("爱要怎么说出口", "赵传"),
    ("红日", "李克勤"),
    ("护花使者", "李克勤"),
    ("不是因为寂寞才想你", "TRY"),
    ("风继续吹", "张国荣"),
    ("风中的承诺", "李翊君"),
    ("不要在我寂寞的时候说爱我", "TRY"),
    ("如果云知道", "许茹芸"),
    ("特别的爱给特别的你", "伍思凯"),
    ("天竺少女", "李玲玉"),
    ("月亮惹的祸", "张宇"),
    ("青苹果乐园", "小虎队"),
    ("明月千里寄相思", "徐小凤"),
    ("我的中国心", "张明敏"),
    ("驼铃", "蒋大为"),
    ("北国之春", "蒋大为"),
    ("我恨我痴心", "刘德华"),
    ("情人", "Beyond"),
    ("情书", "张学友"),
    ("我不想说", "杨钰莹"),
    ("篱笆墙的影子", "毛阿敏"),
    ("爱你十分泪七分", "裘海正"),
    ("有没有一首歌会让你想起我", "周华健"),
    ("爱上一个不回家的人", "林忆莲"),
    ("轻轻的告诉你", "杨钰莹"),
    ("雨蝶", "李翊君"),
    ("光阴的故事", "罗大佑"),
    ("睡在我上铺的兄弟", "老狼"),
    ("鲁冰花", "甄妮"),
    ("只想一生跟你走", "张学友"),
    ("男儿当自强", "林子祥"),
    ("千言万语", "邓丽君"),
    ("爱在深秋", "谭咏麟"),
    ("亲亲我的宝贝", "周华健"),
    ("渴望", "毛阿敏"),
    ("安妮", "王杰"),
    ("兰花草", "刘文正"),
    ("你的柔情我永远不懂", "陈琳"),
    ("好大一棵树", "田震"),
    ("你最珍贵", "张学友"),
    ("烛光里的妈妈", "毛阿敏"),
    ("纤夫的爱", "尹相杰"),
    ("你看你看月亮的脸", "孟庭苇"),
    ("今夜你会不会来", "黎明"),
    ("笑红尘", "陈淑桦"),
    ("我终于失去了你", "赵传"),
    ("耶利亚女郎", "童安格"),
    ("逝去的诺言", "陈慧娴"),
    ("忘记你我做不到", "张学友"),
    ("野百合也有春天", "罗大佑"),
    ("婉君", "李翊君"),
    ("笨小孩", "刘德华"),
    ("亲密爱人", "梅艳芳"),
    ("我愿意", "王菲"),
    ("彩虹", "羽泉"),
    ("无情的雨无情的你", "齐秦"),
    ("不装饰你的梦", "蔡国权"),
    ("我被青春撞了一下腰", "张真"),
    ("小芳", "李春波"),
    ("心如刀割", "张学友"),
    ("不是我不小心", "张镐哲"),
    ("野花", "田震"),
    ("冬天里的一把火", "费翔"),
    ("想和你去吹吹风", "张学友"),
    ("垄上行", "张明敏"),
    ("东方之珠", "罗大佑"),
    ("星光依旧灿烂", "小虎队"),
    ("红尘有你", "王杰"),
    ("十七岁的雨季", "林志颖"),
    ("回头太难", "张学友"),
    ("九妹", "黄鹤翔"),
    ("别问我是谁", "王馨平"),
    ("恋曲1980", "罗大佑"),
    ("一千零一夜", "邰正宵"),
    ("铿锵玫瑰", "林忆莲"),
    ("白天不懂夜的黑", "那英"),
    ("一无所有", "崔健"),
    ("一言难尽", "张宇"),
    ("念亲恩", "陈百强"),
    ("找一个字代替", "邰正宵"),
    ("鬼迷心窍", "李宗盛"),
    ("爱的代价", "张艾嘉"),
    ("月朦胧鸟朦胧", "凤飞飞"),
    ("狼", "齐秦"),
    ("皇后大道东", "罗大佑"),
    ("不老的传说", "张学友"),
    ("长城", "Beyond"),
    ("当年情", "张国荣"),
    ("祝你平安", "孙悦"),
    ("曾经心疼", "叶倩文"),
    ("似是故人来", "梅艳芳"),
    ("心要让你听见", "邰正宵"),
    ("南海姑娘", "邓丽君"),
    ("半梦半醒", "谭咏麟"),
    ("你快回来", "孙楠"),
    ("风再起时", "张国荣"),
    ("只要你过得比我好", "钟镇涛"),
    ("随缘", "温兆伦"),
    ("我很丑可是我很温柔", "赵传"),
    ("敢问路在何方", "蒋大为"),
    ("每天爱你多一些", "张学友"),
    ("笑脸", "谢东"),
    ("女人何苦为难女人", "辛晓琪"),
    ("宽容", "张信哲"),
    ("囚鸟", "张宇"),
    ("游戏人间", "郑智化"),
    ("想你的时候", "千百惠"),
    ("一世情缘", "童安格"),
    ("香水有毒", "胡杨林"),
    ("女人花", "梅艳芳"),
    ("明明白白我的心", "陈淑桦"),
    ("真心真意过一生", "叶倩文"),
    ("思念", "毛阿敏"),
    ("天涯歌女", "徐小凤"),
    ("一天到晚游泳的鱼", "张雨生"),
    ("Amani", "Beyond"),
    ("爱的奉献", "韦唯"),
    ("堆积情感", "邝美云"),
    ("我和春天有个约会", "邝美云"),
    ("几度夕阳红", "潘越云"),
    ("稻草人", "林志颖"),
    ("顺流逆流", "徐小凤"),
    ("最爱上海滩", "刘德华"),
    ("真我的风采", "刘德华"),
    ("天若有情", "高胜美"),
    ("为了爱梦一生", "王杰"),
    ("情凭谁来定错对", "谭咏麟"),
    ("绿岛小夜曲", "蔡幸娟"),
    ("星星知我心", "蔡幸娟"),
    ("偷心", "张学友"),
    ("当", "动力火车"),
    ("回家", "顺子"),
    ("穿过你的黑发的我的手", "罗大佑"),
    ("外面的世界", "齐秦"),
    ("你知道我在等你吗", "张洪量"),
    ("情已逝", "张学友"),
    ("一生中最爱", "谭咏麟"),
    ("大国民", "郑智化"),
    ("无语问苍天", "高胜美"),
    ("好好爱我", "张蔷"),
    ("勇敢一点", "赵传"),
    ("不必在乎我是谁", "林忆莲"),
    ("爱一回伤一回", "吕方"),
    ("捕风的汉子", "谭咏麟"),
    ("让我一次爱个够", "庾澄庆"),
    ("玻璃心", "齐秦"),
    ("让一切随风", "钟镇涛"),
    ("笑忘书", "王菲"),
    ("大中国", "高枫"),
    ("真的还是假的", "孟庭苇"),
    ("爱是永恒", "张学友"),
    ("忘情森巴舞", "草蜢"),
    ("春风吻上我的脸", "凤飞飞"),
    ("粉红色的回忆", "韩宝仪"),
    ("光辉岁月", "Beyond"),
    ("摘下满天星", "郑少秋"),
    ("季候风", "王菲"),
    ("广岛之恋", "张洪量"),
    ("相思成灾", "刘德华"),
    ("得意的笑", "李丽芬"),
    ("一天一点爱恋", "梁朝伟"),
    ("爱情鸟", "林依轮"),
    ("牵挂你的人是我", "高林生"),
    ("七天七世纪", "李天华"),
    ("京华春梦", "汪明荃"),
    ("我是不是你最疼爱的人", "潘越云"),
    ("爱之初体验", "张震岳"),
    ("失恋阵线联盟", "草蜢"),
    ("寂寞让我如此美丽", "陈明"),
    ("一封家书", "李春波"),
    ("情未了", "黄凯芹"),
    ("听说爱情回来过", "林忆莲"),
    ("真的汉子", "林子祥"),
    ("回到拉萨", "郑钧"),
    ("绿叶对根的情意", "毛阿敏"),
    ("每一步", "徐小凤"),
    ("口是心非", "张雨生"),
    ("错过你错过爱", "张信哲"),
    ("选择", "林子祥"),
    ("绝口不提爱你", "郑中基"),
    ("走四方", "韩磊"),
    ("领悟", "辛晓琪"),
    ("最近比较烦", "周华健"),
    ("忘了你忘了我", "王杰"),
    ("忘记他", "邓丽君"),
    ("太想爱你", "张信哲"),
    ("年轻时代", "郑智化"),
    ("浪子心声", "许冠杰"),
    ("堕落天使", "郑智化"),
    ("夜太黑", "林忆莲"),
    ("追风少年", "吴奇隆"),
    ("红颜美人多薄命", "伊能静"),
    ("似水流年", "梅艳芳"),
    ("奉献", "苏芮"),
    ("四季歌", "达明一派"),
    ("彼岸花", "王菲"),
    ("不", "陈百强"),
    ("我是真的爱你", "张信哲"),
    ("说谎", "温兆伦"),
    ("一颗不变心", "张学友"),
    ("卡拉永远OK", "谭咏麟"),
    ("在雨中", "刘家昌"),
    ("天天想你", "张雨生"),
    ("春去春又回", "陈淑桦"),
    ("我独自在风雨中", "高明骏"),
    ("再见理想", "Beyond"),
    ("尘缘", "罗文"),
    ("不了情", "徐小凤"),
    ("为什么我的真换来我的疼", "高胜美"),
    ("思念总在分手后", "刘文正"),
    ("流星下的愿", "张学友"),
    ("为什么受伤的总是我", "林志颖"),
    ("一天一天等下去", "吴奇隆"),
    ("无地自容", "黑豹乐队"),
    ("含羞草", "翁倩玉"),
    ("对你爱不完", "郭富城"),
    ("你是我心底的烙印", "钟镇涛"),
    ("想哭就哭", "姜育恒"),
    ("伤感的恋人", "黄凯芹"),
    ("我拿什么爱你", "齐秦"),
    ("最爱", "周慧敏"),
    ("亚洲雄风", "韦唯"),
    ("青春舞曲", "罗大佑"),
    ("你把我的女人带走", "温兆伦"),
    ("但愿人长久", "邓丽君"),
    ("十送红军", "宋祖英"),
    ("初恋情人", "刘小慧"),
    ("镜花水月", "梅艳芳"),
    ("夜上海", "周璇"),
    ("赤裸裸", "郑钧"),
    ("一人有一个梦想", "黎瑞恩"),
    ("我的眼里只有你", "景岗山"),
    ("难得有情人", "关淑怡"),
    ("梦回唐朝", "唐朝乐队"),
    ("你快乐所以我快乐", "王菲"),
    ("是不是这样的夜晚你才会想起我", "吴宗宪"),
    ("蓝雨", "张学友"),
    ("长城谣", "张明敏"),
    ("恋恋风尘", "陈慧娴"),
    ("不后悔", "张学友"),
    ("谁的心忘了收", "孙楠"),
    ("用我一辈子去忘记", "郑智化"),
    ("摆渡人的歌", "周华健"),
    ("像我这样的朋友", "谭咏麟"),
    ("上上签", "周华健"),
    ("亲爱的小孩", "苏芮"),
    ("坏女孩", "梅艳芳"),
    ("永远不回头", "张雨生"),
    ("那一夜你喝了酒", "陈淑桦"),
    ("我的爱对你说", "叶倩文"),
    ("我是真的付出我的爱", "周华健"),
    ("爱人同志", "罗大佑"),
    ("寂寞的眼", "周华健"),
    ("寡妇村传奇", "周华健"),
    ("流浪的小孩", "伊能静"),
    ("那个傻瓜爱过你", "赵传"),
    ("直觉", "张信哲"),
    ("海上花", "甄妮"),
    ("白衣飘飘的年代", "叶蓓"),
    ("我所爱的让我流泪", "赵传"),
    ("流星", "王菲"),
    ("相约到永久", "关之琳"),
    ("只记今朝笑", "林青霞"),
    ("为你钟情", "张国荣"),
    ("你的眼神", "林志美"),
    ("我心已许", "蔡幸娟"),
    ("雨中的恋人们", "黄凯芹"),
    ("婚纱背后", "徐小凤"),
    ("爱情故事", "辛晓琪"),
    ("蝶恋花", "黄凯芹"),
    ("还是朋友", "张雨生"),
    ("花房姑娘", "崔健"),
    ("我们的故事", "赵咏华"),
    ("我是一棵秋天的树", "张雨生"),
    ("生日快乐", "伊能静"),
    ("花季未了", "刘若英"),
    ("新长征路上的摇滚", "崔健"),
    ("十九岁的最后一天", "伊能静"),
    ("想你想得好孤寂", "邰正宵"),
    ("让爱继续", "谭咏麟"),
    ("石头记", "达明一派"),
    ("如果还有明天", "刘伟仁"),
    ("天长地久", "周启生"),
    ("萤火虫", "伊能静"),
    ("鸳鸯锦", "叶欢"),
    ("难以抗拒", "李度"),
    ("偷偷爱你", "梁朝伟"),
    ("钟爱一生", "杜德伟"),
    ("千愁记旧情", "罗文"),
    ("大会堂演奏厅", "李克勤"),
    ("流光飞舞", "陈淑桦"),
    ("轻抚你的脸", "张学友"),
    ("爱你", "郭富城"),
    ("灰色", "林忆莲"),
    ("初恋", "红孩儿"),
    ("深深深", "李克勤"),
    ("来来回回", "张学友"),
    ("星光灿烂", "罗中旭"),
    ("如果可以再见你", "黎明"),
    ("老朋友", "邰正宵"),
    ("屋顶", "吴宗宪"),
    ("我应该", "张学友"),
    ("姐姐", "张楚"),
    ("美丽的花蝴蝶", "张洪量"),
    ("不走", "杜德伟"),
    ("摘星的晚上", "李国祥"),
    ("海角天涯", "刘锡明"),
    ("未了情", "郭富城"),
    ("想你", "范文芳"),
    ("天下没有不散的筵席", "郑钧"),
    ("不是每个恋曲都有美好回忆", "林志颖"),
    ("带我去月球", "张雨生"),
    ("军中绿花", "小曾"),
    ("我期待", "张雨生"),
    ("傻瓜", "苏慧伦"),
    ("命运是你家", "Beyond"),
    ("冰点与沸点", "周海媚"),
    ("非常夏日", "王菲"),
    ("甜蜜蜜", "邓丽君"),
    ("最真的期待", "赵咏华"),
    ("我的1997", "艾敬"),
    ("我是猫", "伊能静"),
    ("一个人的我依然会微笑", "林佳仪"),
    ("HELLO", "王杰"),
    ("回忆", "钟镇涛"),
    ("倾心", "黄凯芹"),
    ("因为寂寞", "张艾嘉"),
    ("寂寞公路", "伍思凯"),
    ("有梦有朋友", "伍思凯"),
    ("爱的进行式", "陈淑桦"),
    ("虹", "齐秦"),
    ("失乐园", "陈淑桦"),
    ("两边", "邰正宵"),
    ("不怕付出", "蓝心湄"),
    ("隐形的翅膀", "张韶涵"),
    ("月亮之上", "凤凰传奇"),
    ("突然的自我", "伍佰"),
    ("自由飞翔", "凤凰传奇"),
    ("两只蝴蝶", "庞龙"),
    ("在心里从此永远有个你", "高安"),
    ("在希望的田野上", "彭丽媛"),
    ("丁香花", "唐磊"),
    ("我想更懂你", "潘玮柏"),
    ("狼爱上羊", "汤潮"),
    ("莫呼洛迦", "辛晓琪"),
    ("春光乍泄", "黄耀明"),
    ("改变1995", "黄舒骏"),
    ("信赖", "万芳"),
    ("天路", "韩红"),
    ("听海", "张惠妹"),
    ("过火", "张信哲"),
    ("2002年的第一场雪", "刀郎"),
    ("双节棍", "周杰伦"),
    ("海阔天空", "Beyond"),
    ("中国人", "刘德华"),

    # ==================== 周杰伦歌曲全集 ====================
    ("晴天", "周杰伦"),
    ("七里香", "周杰伦"),
    ("夜曲", "周杰伦"),
    ("稻香", "周杰伦"),
    ("告白气球", "周杰伦"),
    ("听妈妈的话", "周杰伦"),
    ("烟花易冷", "周杰伦"),
    ("菊花台", "周杰伦"),
    ("说好不哭", "周杰伦"),
    ("红尘客栈", "周杰伦"),
    ("牛仔很忙", "周杰伦"),
    ("夜的第七章", "周杰伦"),
    ("开不了口", "周杰伦"),
    ("简单爱", "周杰伦"),
    ("龙卷风", "周杰伦"),
    ("安静", "周杰伦"),
    ("以父之名", "周杰伦"),
    ("青花瓷", "周杰伦"),
    ("兰亭序", "周杰伦"),
    ("发如雪", "周杰伦"),
    ("千里之外", "周杰伦"),
    ("东风破", "周杰伦"),
    ("不能说的秘密", "周杰伦"),
    ("一路向北", "周杰伦"),
    ("可爱女人", "周杰伦"),
    ("星晴", "周杰伦"),
    ("黑色幽默", "周杰伦"),
    ("半岛铁盒", "周杰伦"),
    ("双截棍", "周杰伦"),
    ("搁浅", "周杰伦"),
    ("断了的弦", "周杰伦"),
    ("枫", "周杰伦"),
    ("彩虹", "周杰伦"),
    ("珊瑚海", "周杰伦"),
    ("蒲公英的约定", "周杰伦"),
    ("最长的电影", "周杰伦"),
    ("给我一首歌的时间", "周杰伦"),
    ("说好的幸福呢", "周杰伦"),
    ("算什么男人", "周杰伦"),
    ("等你下课", "周杰伦"),
    ("Mojito", "周杰伦"),
    ("我是如此相信", "周杰伦"),
    ("不爱我就拉倒", "周杰伦"),
    ("听见下雨的声音", "周杰伦"),

    # ==================== 林俊杰歌曲 ====================
    ("江南", "林俊杰"),
    ("一千年以后", "林俊杰"),
    ("醉赤壁", "林俊杰"),
    ("关键词", "林俊杰"),
    ("学不会", "林俊杰"),
    ("期待爱", "林俊杰"),
    ("修炼爱情", "林俊杰"),
    ("她说", "林俊杰"),
    ("可惜没如果", "林俊杰"),
    ("不为谁而作的歌", "林俊杰"),
    ("背对背拥抱", "林俊杰"),
    ("小酒窝", "林俊杰"),
    ("曹操", "林俊杰"),
    ("美人鱼", "林俊杰"),
    ("编号89757", "林俊杰"),
    ("冻结", "林俊杰"),
    ("豆浆油条", "林俊杰"),
    ("不潮不用花钱", "林俊杰"),
    ("将故事写成我们", "林俊杰"),
    ("交换余生", "林俊杰"),

    # ==================== 陈奕迅歌曲 ====================
    ("十年", "陈奕迅"),
    ("浮夸", "陈奕迅"),
    ("好久不见", "陈奕迅"),
    ("红玫瑰", "陈奕迅"),
    ("爱情转移", "陈奕迅"),
    ("不要说话", "陈奕迅"),
    ("陪你度过漫长岁月", "陈奕迅"),
    ("富士山下", "陈奕迅"),
    ("K歌之王", "陈奕迅"),
    ("你的背包", "陈奕迅"),
    ("淘汰", "陈奕迅"),
    ("最佳损友", "陈奕迅"),
    ("单车", "陈奕迅"),
    ("谢谢侬", "陈奕迅"),
    ("孤独患者", "陈奕迅"),
    ("因为爱情", "陈奕迅"),

    # ==================== 邓紫棋歌曲 ====================
    ("泡沫", "G.E.M.邓紫棋"),
    ("光年之外", "G.E.M.邓紫棋"),
    ("夜空中最亮的星", "G.E.M.邓紫棋"),
    ("龙卷风", "G.E.M.邓紫棋"),
    ("喜欢你", "G.E.M.邓紫棋"),
    ("倒数", "G.E.M.邓紫棋"),
    ("来自天堂的魔鬼", "G.E.M.邓紫棋"),
    ("画", "G.E.M.邓紫棋"),
    ("我的秘密", "G.E.M.邓紫棋"),
    ("句号", "G.E.M.邓紫棋"),
    ("摩天动物园", "G.E.M.邓紫棋"),
    ("透明", "G.E.M.邓紫棋"),
    ("多远都要在一起", "G.E.M.邓紫棋"),

    # ==================== 五月天歌曲 ====================
    ("倔强", "五月天"),
    ("知足", "五月天"),
    ("突然好想你", "五月天"),
    ("温柔", "五月天"),
    ("恋爱ing", "五月天"),
    ("如果我们不曾相遇", "五月天"),
    ("孙悟空", "五月天"),
    ("你不是真正的快乐", "五月天"),
    ("干杯", "五月天"),
    ("拥抱", "五月天"),
    ("后来的我们", "五月天"),
    ("我不愿让你一个人", "五月天"),
    ("步步", "五月天"),
    ("伤心的人别听慢歌", "五月天"),
    ("派对动物", "五月天"),

    # ==================== 张杰歌曲 ====================
    ("仰望星空", "张杰"),
    ("逆战", "张杰"),
    ("天下", "张杰"),
    ("他不懂", "张杰"),
    ("剑心", "张杰"),
    ("逆态度", "张杰"),
    ("何必要在一起", "张杰"),
    ("如果爱", "张杰"),
    ("这就是爱", "张杰"),
    ("明天过后", "张杰"),
    ("第一夫人", "张杰"),
    ("勿忘心安", "张杰"),
    ("三生三世", "张杰"),

    # ==================== 2024-2025 热门华语歌曲 ====================
    ("世界赠予我的", "王菲"),
    ("珠玉", "单依纯"),
    ("好风起", "周深"),
    ("小美满", "周深"),
    ("花开忘忧", "周深"),
    ("在月蚀里抱紧我", "林俊杰"),
    ("像晴天像雨天", "汪苏泷"),
    ("命运的赛勒克", "刀郎"),
    ("先说爱的人为什么先离开", "田园"),
    ("搀扶", "马健涛"),
    ("土坡上的狗尾草", "卢润泽"),
    ("跳楼机", "LBI利比"),
    ("消散对白", "丁禹兮"),
    ("大概", "王俊凯"),
    ("大展鸿图", "揽佬"),
    ("四点的海棠花未眠", "渡"),
    ("第57次取消发送", "菲菲公主"),
    ("背着风流泪", "文夫"),
    ("不要回头", "肖战"),
    ("亲爱的你啊", "任素汐"),
    ("月亮照山川", "窝窝"),
    ("鬼屋", "林宥嘉"),
    ("千言万语", "陶喆"),
    ("果實", "陈粒"),
    ("轻功水上飘", "黄宣"),
    ("奇卡奇卡", "裘德"),
    ("避世离俗", "梁博"),
    ("有趣", "单依纯"),
    ("一念之间", "吴青峰"),
    ("偏见", "deca joins"),
    ("蕾丝花边", "周华健"),
    ("堤防", "老王乐队"),
    ("没出息", "王搏"),
    ("就是哪吒", "唐汉霄"),
    ("西楼别序", "张云雷"),
    ("雨后晴天", "梓渝"),
    ("庙堂之外", "陈楚生"),
    ("千万次想象", "张杰"),
    ("羽毛剑", "秦凡淇"),
    ("岁岁年年", "肖战"),
    ("野心家", "张靓颖"),
    ("昔涟", "张韶涵"),

    # ==================== 更多现代华语热歌 ====================
    ("起风了", "买辣椒也用券"),
    ("孤勇者", "陈奕迅"),
    ("错位时空", "艾辰"),
    ("踏山河", "是七叔呢"),
    ("半生雪", "是七叔呢"),
    ("燕无歇", "蒋雪儿"),
    ("芒种", "赵方婧"),
    ("少年", "梦然"),
    ("后来遇见他", "胡66"),
    ("你的答案", "阿冗"),
    ("飞鸟和蝉", "任然"),
    ("白月光与朱砂痣", "大籽"),
    ("大风吹", "王赫野"),
    ("星辰大海", "黄霄云"),
    ("千千万万", "深海鱼子酱"),
    ("清空", "王忻辰"),
    ("特别邀请", "ycccc"),
    ("沉醉的青丝", "李常超"),
    ("执迷不悟", "小乐哥"),
    ("云与海", "阿YueYue"),
    ("赤伶", "HITA"),
    ("虞兮叹", "闻人听书"),
    ("海底", "一支榴莲"),
    ("可可托海的牧羊人", "王琪"),
    ("点歌的人", "海来阿木"),
    ("不过人间", "海来阿木"),
    ("别知己", "海来阿木"),
    ("送亲", "王琪"),
    ("万疆", "李玉刚"),
    ("骁", "井胧"),
    ("年岁", "河图"),
    ("人间惊鸿客", "叶里"),
    ("囍", "葛东琪"),
    ("下山", "要不要买菜"),
    ("盗将行", "花粥"),
    ("出山", "花粥"),
    ("归去来兮", "花粥"),
    ("绿色", "陈雪凝"),
    ("你的酒馆对我打了烊", "陈雪凝"),
    ("往后余生", "马良"),
    ("可不可以", "张紫豪"),
    ("侧脸", "于果"),
    ("病变", "鞠文娴"),
    ("体面", "于文文"),
    ("说散就散", "袁娅维"),
    ("追光者", "岑宁儿"),
    ("凉凉", "杨宗纬"),
    ("年少有为", "李荣浩"),
    ("作曲家", "李荣浩"),
    ("李白", "李荣浩"),
    ("不将就", "李荣浩"),
    ("麻雀", "李荣浩"),
    ("戒烟", "李荣浩"),
    ("爸爸妈妈", "李荣浩"),

    # ==================== 更多华语经典 ====================
    ("月亮代表我的心", "邓丽君"),
    ("我只在乎你", "邓丽君"),
    ("再见我的爱人", "邓丽君"),
    ("偿还", "邓丽君"),
    ("爱人", "邓丽君"),
    ("如果没有你", "邓丽君"),
    ("爱的箴言", "邓丽君"),
    ("传奇", "王菲"),
    ("红豆", "王菲"),
    ("因为爱情", "王菲"),
    ("匆匆那年", "王菲"),
    ("约定", "王菲"),
    ("天空", "王菲"),
    ("暗涌", "王菲"),
    ("暧昧", "王菲"),
    ("百年孤寂", "王菲"),
    ("平凡之路", "朴树"),
    ("白桦林", "朴树"),
    ("生如夏花", "朴树"),
    ("那些花儿", "朴树"),
    ("New Boy", "朴树"),
    ("送别", "朴树"),
    ("清白之年", "朴树"),
    ("蓝莲花", "许巍"),
    ("曾经的你", "许巍"),
    ("故乡", "许巍"),
    ("完美生活", "许巍"),
    ("像风一样自由", "许巍"),
    ("旅行", "许巍"),
    ("成都", "赵雷"),
    ("南方姑娘", "赵雷"),
    ("理想", "赵雷"),
    ("阿刁", "赵雷"),
    ("鼓楼", "赵雷"),
    ("三十岁的女人", "赵雷"),
    ("画", "赵雷"),
    ("春风十里", "鹿先森乐队"),
    ("往后余生", "马良"),
    ("盗将行", "花粥"),
    ("理想三旬", "陈鸿宇"),
    ("南山南", "马頔"),
    ("傲寒", "马頔"),
    ("董小姐", "宋冬野"),
    ("斑马斑马", "宋冬野"),
    ("安和桥", "宋冬野"),
    ("莉莉安", "宋冬野"),
    ("关于郑州的记忆", "李志"),
    ("天空之城", "李志"),
    ("山阴路的夏天", "李志"),
    ("梵高先生", "李志"),
    ("这个世界会好吗", "李志"),
    ("突然好想你", "五月天"),
    ("你不是真正的快乐", "五月天"),

    # ==================== 英文经典热门 ====================
    ("Yesterday", "The Beatles"),
    ("Hey Jude", "The Beatles"),
    ("Let It Be", "The Beatles"),
    ("Imagine", "John Lennon"),
    ("Bohemian Rhapsody", "Queen"),
    ("We Will Rock You", "Queen"),
    ("Hotel California", "Eagles"),
    ("Stairway to Heaven", "Led Zeppelin"),
    ("Sweet Child O' Mine", "Guns N' Roses"),
    ("November Rain", "Guns N' Roses"),
    ("Nothing Else Matters", "Metallica"),
    ("Smells Like Teen Spirit", "Nirvana"),
    ("Come As You Are", "Nirvana"),
    ("Wonderwall", "Oasis"),
    ("Zombie", "The Cranberries"),
    ("Dreams", "The Cranberries"),
    ("My Heart Will Go On", "Celine Dion"),
    ("The Power of Love", "Celine Dion"),
    ("Rolling in the Deep", "Adele"),
    ("Someone Like You", "Adele"),
    ("Hello", "Adele"),
    ("Skyfall", "Adele"),
    ("Set Fire to the Rain", "Adele"),
    ("Shape of You", "Ed Sheeran"),
    ("Perfect", "Ed Sheeran"),
    ("Thinking Out Loud", "Ed Sheeran"),
    ("Photograph", "Ed Sheeran"),
    ("Castle on the Hill", "Ed Sheeran"),
    ("Shivers", "Ed Sheeran"),
    ("Bad Habits", "Ed Sheeran"),
    ("Blinding Lights", "The Weeknd"),
    ("Save Your Tears", "The Weeknd"),
    ("Starboy", "The Weeknd"),
    ("Uptown Funk", "Mark Ronson"),
    ("Happy", "Pharrell Williams"),
    ("See You Again", "Wiz Khalifa"),
    ("Love Yourself", "Justin Bieber"),
    ("Sorry", "Justin Bieber"),
    ("Baby", "Justin Bieber"),
    ("Peaches", "Justin Bieber"),
    ("Stay", "Justin Bieber"),
    ("Shake It Off", "Taylor Swift"),
    ("Blank Space", "Taylor Swift"),
    ("Love Story", "Taylor Swift"),
    ("You Belong With Me", "Taylor Swift"),
    ("Bad Blood", "Taylor Swift"),
    ("Look What You Made Me Do", "Taylor Swift"),
    ("Cardigan", "Taylor Swift"),
    ("Lover", "Taylor Swift"),
    ("Anti-Hero", "Taylor Swift"),
    ("Cruel Summer", "Taylor Swift"),
    ("Dance Monkey", "Tones and I"),
    ("Old Town Road", "Lil Nas X"),
    ("Despacito", "Luis Fonsi"),
    ("Senorita", "Shawn Mendes"),
    ("Havana", "Camila Cabello"),
    ("Drivers License", "Olivia Rodrigo"),
    ("Good 4 U", "Olivia Rodrigo"),
    ("Vampire", "Olivia Rodrigo"),
    ("Flowers", "Miley Cyrus"),
    ("Wrecking Ball", "Miley Cyrus"),
    ("Party in the USA", "Miley Cyrus"),
    ("Counting Stars", "OneRepublic"),
    ("Apologize", "OneRepublic"),
    ("Secrets", "OneRepublic"),
    ("Radioactive", "Imagine Dragons"),
    ("Believer", "Imagine Dragons"),
    ("Thunder", "Imagine Dragons"),
    ("Demons", "Imagine Dragons"),
    ("Natural", "Imagine Dragons"),
    ("Enemy", "Imagine Dragons"),
    ("Bones", "Imagine Dragons"),
    ("Wake Me Up", "Avicii"),
    ("Hey Brother", "Avicii"),
    ("The Nights", "Avicii"),
    ("Waiting for Love", "Avicii"),
    ("Levels", "Avicii"),
    ("Closer", "The Chainsmokers"),
    ("Something Just Like This", "The Chainsmokers"),
    ("Don't Let Me Down", "The Chainsmokers"),
    ("Faded", "Alan Walker"),
    ("Alone", "Alan Walker"),
    ("The Spectre", "Alan Walker"),
    ("Darkside", "Alan Walker"),
    ("On My Way", "Alan Walker"),
    ("Lean On", "Major Lazer"),
    ("Titanium", "David Guetta"),
    ("Without Me", "Eminem"),
    ("Lose Yourself", "Eminem"),
    ("Love The Way You Lie", "Eminem"),
    ("When I'm Gone", "Eminem"),
    ("Not Afraid", "Eminem"),
    ("Stan", "Eminem"),
    ("Rap God", "Eminem"),
    ("Mockingbird", "Eminem"),
    ("God's Plan", "Drake"),
    ("One Dance", "Drake"),
    ("Hotline Bling", "Drake"),
    ("In My Feelings", "Drake"),

    # ==================== Billboard 2024 Year-End Top 50 ====================
    ("Lose Control", "Teddy Swims"),
    ("A Bar Song", "Shaboozey"),
    ("Beautiful Things", "Benson Boone"),
    ("I Had Some Help", "Post Malone"),
    ("Lovin on Me", "Jack Harlow"),
    ("Not Like Us", "Kendrick Lamar"),
    ("Espresso", "Sabrina Carpenter"),
    ("Million Dollar Baby", "Tommy Richman"),
    ("I Remember Everything", "Zach Bryan"),
    ("Too Sweet", "Hozier"),
    ("Stick Season", "Noah Kahan"),
    ("Greedy", "Tate McRae"),
    ("Like That", "Future"),
    ("Birds of a Feather", "Billie Eilish"),
    ("Please Please Please", "Sabrina Carpenter"),
    ("Agora Hills", "Doja Cat"),
    ("Good Luck Babe", "Chappell Roan"),
    ("Saturn", "SZA"),
    ("Snooze", "SZA"),
    ("Paint the Town Red", "Doja Cat"),
    ("Fortnight", "Taylor Swift"),
    ("Fast Car", "Luke Combs"),
    ("Water", "Tyla"),
    ("Feather", "Sabrina Carpenter"),
    ("Austin", "Dasha"),
    ("Last Night", "Morgan Wallen"),
    ("Pink Skies", "Zach Bryan"),
    ("Texas Hold Em", "Beyonce"),
    ("Is It Over Now", "Taylor Swift"),
    ("Miles on It", "Kane Brown"),
    ("Wild Ones", "Jessie Murph"),
    ("Carnival", "Kanye West"),
    ("Houdini", "Eminem"),
    ("Redrum", "21 Savage"),
    ("Houdini", "Dua Lipa"),
    ("What Was I Made For", "Billie Eilish"),
    ("End of Beginning", "Djo"),
    ("Lunch", "Billie Eilish"),
    ("Never Lose Me", "Flo Milli"),
    ("Gata Only", "FloyyMenor"),
    ("Hot to Go", "Chappell Roan"),
    ("Made for Me", "Muni Long"),
    ("Whatever She Wants", "Bryson Tiller"),
    ("Die with a Smile", "Lady Gaga"),
    ("I Like the Way You Kiss Me", "Artemas"),
    ("Euphoria", "Kendrick Lamar"),
    ("Stargazing", "Myles Smith"),
    ("Taste", "Sabrina Carpenter"),
    ("Wildflower", "Billie Eilish"),
    ("Down Bad", "Taylor Swift"),

    # ==================== K-Pop 热门歌曲 ====================
    ("Supernova", "aespa"),
    ("Drama", "aespa"),
    ("Spicy", "aespa"),
    ("Armageddon", "aespa"),
    ("Whiplash", "aespa"),
    ("Fate", "(G)I-DLE"),
    ("Queencard", "(G)I-DLE"),
    ("Klaxon", "(G)I-DLE"),
    ("Super Lady", "(G)I-DLE"),
    ("Wife", "(G)I-DLE"),
    ("Love wins all", "IU"),
    ("Someday", "IU"),
    ("Holssi", "IU"),
    ("I AM", "IVE"),
    ("HEYA", "IVE"),
    ("LOVE DIVE", "IVE"),
    ("Baddie", "IVE"),
    ("Kitsch", "IVE"),
    ("After LIKE", "IVE"),
    ("Hype Boy", "NewJeans"),
    ("Ditto", "NewJeans"),
    ("OMG", "NewJeans"),
    ("Super Shy", "NewJeans"),
    ("ETA", "NewJeans"),
    ("How Sweet", "NewJeans"),
    ("Bubble Gum", "NewJeans"),
    ("Attention", "NewJeans"),
    ("Magnetic", "ILLIT"),
    ("SHEESH", "BABYMONSTER"),
    ("Perfect Night", "LE SSERAFIM"),
    ("EASY", "LE SSERAFIM"),
    ("Smart", "LE SSERAFIM"),
    ("Maniac", "VIVIZ"),
    ("plot twist", "TWS"),
    ("Seven", "Jungkook"),
    ("Standing Next to You", "Jungkook"),
    ("Like Crazy", "Jimin"),
    ("APT", "Rose"),
    ("You and Me", "Jennie"),
    ("SPOT", "Zico"),
    ("Love 119", "RIIZE"),
    ("Get A Guitar", "RIIZE"),
    ("Boom Boom Bass", "RIIZE"),
    ("Super", "SEVENTEEN"),
    ("God of Music", "SEVENTEEN"),
    ("Fighting", "BSS"),
    ("Sticky", "KISS OF LIFE"),
    ("Dynamite", "BTS"),
    ("Spring Day", "BTS"),
    ("Butter", "BTS"),
    ("Permission to Dance", "BTS"),
    ("Boy With Luv", "BTS"),
    ("Life Goes On", "BTS"),
    ("Fake Love", "BTS"),
    ("IDOL", "BTS"),
    ("DNA", "BTS"),
    ("The First Snow", "EXO"),
    ("Love Shot", "EXO"),
    ("Ko Ko Bop", "EXO"),
    ("Growl", "EXO"),
    ("To. X", "Taeyeon"),
    ("Dream", "Taeyeon"),
    ("Stay", "BLACKPINK"),
    ("How You Like That", "BLACKPINK"),
    ("Kill This Love", "BLACKPINK"),
    ("DDU-DU DDU-DU", "BLACKPINK"),
    ("Pink Venom", "BLACKPINK"),
    ("Shut Down", "BLACKPINK"),
    ("Solo", "Jennie"),
    ("LALISA", "Lisa"),
    ("On The Ground", "Rose"),
    ("Gone", "Rose"),
    ("Flower", "Jisoo"),
    ("Sugar Rush Ride", "TXT"),
    ("Chasing That Feeling", "TXT"),
    ("S-Class", "Stray Kids"),
    ("MANIAC", "Stray Kids"),
    ("God's Menu", "Stray Kids"),
    ("Thunderous", "Stray Kids"),
    ("CASE 143", "Stray Kids"),
    ("Fancy", "TWICE"),
    ("Feel Special", "TWICE"),
    ("The Feels", "TWICE"),
    ("Cheer Up", "TWICE"),
    ("TT", "TWICE"),
    ("What is Love", "TWICE"),
    ("Alcohol-Free", "TWICE"),
    ("Next Level", "aespa"),
    ("DALLA DALLA", "ITZY"),
    ("WANNABE", "ITZY"),
    ("Fiesta", "IZONE"),
    ("ELEVEN", "IVE"),

    # ==================== 日本动漫/游戏歌曲 ====================
    ("红莲华", "LiSA"),
    ("炎", "LiSA"),
    ("Gurenge", "LiSA"),
    ("千本樱", "初音未来"),
    ("World is Mine", "初音未来"),
    ("Lemon", "米津玄师"),
    ("打上花火", "米津玄师"),
    ("LOSER", "米津玄师"),
    ("KICK BACK", "米津玄师"),
    ("Peace Sign", "米津玄师"),
    ("idol", "YOASOBI"),
    ("夜驱", "YOASOBI"),
    ("群青", "YOASOBI"),
    ("祝福", "YOASOBI"),
    ("怪物", "YOASOBI"),
    ("勇者", "YOASOBI"),
    ("三原色", "YOASOBI"),
    ("青鸟", "生物股长"),
    ("Butter-Fly", "和田光司"),
    ("Brave Heart", "宫崎步"),
    ("One Day", "The Rootless"),
    ("We Are", "北谷洋"),
    ("Hope", "安室奈美惠"),
    ("シルエット", "KANA-BOON"),
    ("ピースサイン", "米津玄师"),
    ("Snow halation", "μ's"),
    ("Don't say lazy", "樱高轻音部"),
    ("God knows", "平野绫"),
    ("Unravel", "TK from 凛として时雨"),
    ("The World", "Nightmare"),
    ("Again", "YUI"),
    ("Rain", "SID"),
    ("Hero's Come Back", "nobodyknows+"),
    ("Cha-La Head-Cha-La", "影山浩宣"),
    ("残酷天使的纲领", "高桥洋子"),
    ("直到世界尽头", "WANDS"),
    ("好想大声说爱你", "BAAD"),
    ("捕捉闪耀的瞬间", "MANISH"),
    ("My Friend", "ZARD"),
    ("转动命运之轮", "ZARD"),
    ("Time after time", "仓木麻衣"),
    ("Secret of my heart", "仓木麻衣"),
    ("Always", "仓木麻衣"),
    ("Can You Feel The Love Tonight", "Elton John"),
    ("Let It Go", "Idina Menzel"),
    ("Try Everything", "Shakira"),
    ("Remember Me", "Miguel"),

    # ==================== 影视原声 ====================
    ("The Children", "Ramin Djawadi"),
    ("Light of the Seven", "Ramin Djawadi"),
    ("Main Title", "Ramin Djawadi"),
    ("He's a Pirate", "Hans Zimmer"),
    ("Time", "Hans Zimmer"),
    ("Now We Are Free", "Hans Zimmer"),
    ("Cornfield Chase", "Hans Zimmer"),
    ("Interstellar Main Theme", "Hans Zimmer"),
    ("Theme from Jurassic Park", "John Williams"),
    ("Star Wars Main Theme", "John Williams"),
    ("Hedwig's Theme", "John Williams"),
    ("The Imperial March", "John Williams"),
    ("My Heart Will Go On", "Celine Dion"),
    ("I Will Always Love You", "Whitney Houston"),
    ("Unchained Melody", "The Righteous Brothers"),
    ("Take My Breath Away", "Berlin"),
    ("The Sound of Silence", "Simon & Garfunkel"),
    ("Scarborough Fair", "Simon & Garfunkel"),
    ("500 Miles", "The Brothers Four"),
    ("Lemon Tree", "Fool's Garden"),
    ("Yesterday Once More", "Carpenters"),
    ("Top of the World", "Carpenters"),
    ("Rhythm of the Rain", "The Cascades"),
    ("Sealed with a Kiss", "Brian Hyland"),
    ("More Than I Can Say", "Leo Sayer"),
    ("Casablanca", "Bertie Higgins"),
    ("Right Here Waiting", "Richard Marx"),
    ("Say You Say Me", "Lionel Richie"),
    ("Careless Whisper", "George Michael"),
    ("Heal the World", "Michael Jackson"),
    ("Beat It", "Michael Jackson"),
    ("Billie Jean", "Michael Jackson"),
    ("Thriller", "Michael Jackson"),
    ("Dangerous", "Michael Jackson"),
    ("Earth Song", "Michael Jackson"),
    ("We Are the World", "Michael Jackson"),
    ("You Are Not Alone", "Michael Jackson"),

    # ==================== 更多华语歌手歌曲 ====================
    ("小幸运", "田馥甄"),
    ("你就不要想起我", "田馥甄"),
    ("魔鬼中的天使", "田馥甄"),
    ("寂寞寂寞就好", "田馥甄"),
    ("Love", "田馥甄"),
    ("一吻之间", "张碧晨"),
    ("下一秒", "张碧晨"),
    ("凉凉", "张碧晨"),
    ("年轮", "张碧晨"),
    ("无问", "毛不易"),
    ("消愁", "毛不易"),
    ("像我这样的人", "毛不易"),
    ("借", "毛不易"),
    ("平凡的一天", "毛不易"),
    ("牧马城市", "毛不易"),
    ("不染", "毛不易"),
    ("东北民谣", "毛不易"),
    ("大城小爱", "王力宏"),
    ("唯一", "王力宏"),
    ("你不知道的事", "王力宏"),
    ("心中的日月", "王力宏"),
    ("改变自己", "王力宏"),
    ("Forever Love", "王力宏"),
    ("龙的传人", "王力宏"),
    ("天外来物", "薛之谦"),
    ("演员", "薛之谦"),
    ("认真的雪", "薛之谦"),
    ("丑八怪", "薛之谦"),
    ("绅士", "薛之谦"),
    ("刚刚好", "薛之谦"),
    ("我好像在哪见过你", "薛之谦"),
    ("像风一样", "薛之谦"),
    ("违背的青春", "薛之谦"),
    ("天后", "陈势安"),
    ("我乐意", "许嵩"),
    ("素颜", "许嵩"),
    ("多余的解释", "许嵩"),
    ("有何不可", "许嵩"),
    ("清明雨上", "许嵩"),
    ("玫瑰花的葬礼", "许嵩"),
    ("断桥残雪", "许嵩"),
    ("山水之间", "许嵩"),
    ("燕归巢", "许嵩"),
    ("K歌之王", "李克勤"),
    ("月半小夜曲", "李克勤"),
    ("富士山下", "李克勤"),
    ("六月的雨", "胡歌"),
    ("忘记时间", "胡歌"),
    ("逍遥叹", "胡歌"),
    ("一吻天荒", "胡歌"),
    ("千里之外", "费玉清"),
    ("一剪梅", "费玉清"),
    ("梦驼铃", "费玉清"),
    ("在水一方", "费玉清"),
    ("晚安曲", "费玉清"),
    ("得意的笑", "李丽芬"),
    ("爱不释手", "李丽芬"),
    ("沧海一声笑", "黄霑"),
    ("倩女幽魂", "张国荣"),
    ("当爱已成往事", "张国荣"),
    ("最冷一天", "张国荣"),
    ("追", "张国荣"),
    ("春夏秋冬", "张国荣"),
    ("我", "张国荣"),
    ("玻璃之情", "张国荣"),
    ("左右手", "张国荣"),
    ("怪你过分美丽", "张国荣"),
    ("光辉岁月", "Beyond"),
    ("海阔天空", "Beyond"),
    ("真的爱你", "Beyond"),
    ("大地", "Beyond"),
    ("不再犹豫", "Beyond"),
    ("灰色轨迹", "Beyond"),
    ("无悔这一生", "Beyond"),
    ("长城", "Beyond"),
    ("情人", "Beyond"),
    ("AMANI", "Beyond"),
    ("再见理想", "Beyond"),
    ("冷雨夜", "Beyond"),
    ("遥远的她", "Beyond"),

    # ==================== 纯音乐/新世纪 ====================
    ("River Flows in You", "Yiruma"),
    ("Kiss the Rain", "Yiruma"),
    ("A Thousand Years", "The Piano Guys"),
    ("Let It Go", "The Piano Guys"),
    ("Canon in D", "Johann Pachelbel"),
    ("Für Elise", "Beethoven"),
    ("Clair de Lune", "Debussy"),
    ("Nocturne Op.9 No.2", "Chopin"),
    ("Spring", "Vivaldi"),
    ("The Four Seasons", "Vivaldi"),
    ("Eine Kleine Nachtmusik", "Mozart"),
    ("Turkish March", "Mozart"),
    ("Ave Maria", "Schubert"),
    ("The Blue Danube", "Johann Strauss"),
    ("Carmen Overture", "Bizet"),
    ("Swan Lake", "Tchaikovsky"),
    ("The Nutcracker", "Tchaikovsky"),
    ("1812 Overture", "Tchaikovsky"),
    ("also sprach Zarathustra", "Richard Strauss"),
    ("Bolero", "Ravel"),
    ("Nuvole Bianche", "Ludovico Einaudi"),
    ("Una Mattina", "Ludovico Einaudi"),
    ("Experience", "Ludovico Einaudi"),
    ("Fly", "Ludovico Einaudi"),
    ("Comptine d'un autre ete", "Yann Tiersen"),
    ("La Valse d'Amelie", "Yann Tiersen"),
    ("Merry Christmas Mr. Lawrence", "坂本龙一"),
    ("Energy Flow", "坂本龙一"),
    ("Rain", "坂本龙一"),
    ("Bibo no Aozora", "坂本龙一"),
    ("梦中的婚礼", "Richard Clayderman"),
    ("星空", "Richard Clayderman"),
    ("秋日私语", "Richard Clayderman"),
    ("致爱丽丝", "Richard Clayderman"),
    ("夜的钢琴曲", "石进"),
    ("天空之城", "久石让"),
    ("Summer", "久石让"),
    ("人生的旋转木马", "久石让"),
    ("千与千寻", "久石让"),
    ("风之甬道", "久石让"),
    ("The Rain", "久石让"),
    ("One Summer's Day", "久石让"),

    # ==================== 更多国际流行 ====================
    ("Memories", "Maroon 5"),
    ("Sugar", "Maroon 5"),
    ("Girls Like You", "Maroon 5"),
    ("Payphone", "Maroon 5"),
    ("Moves Like Jagger", "Maroon 5"),
    ("Animals", "Maroon 5"),
    ("She Will Be Loved", "Maroon 5"),
    ("This Love", "Maroon 5"),
    ("Yellow", "Coldplay"),
    ("Viva La Vida", "Coldplay"),
    ("Fix You", "Coldplay"),
    ("The Scientist", "Coldplay"),
    ("Clocks", "Coldplay"),
    ("Paradise", "Coldplay"),
    ("Hymn for the Weekend", "Coldplay"),
    ("A Sky Full of Stars", "Coldplay"),
    ("Something Just Like This", "Coldplay"),
    ("My Universe", "Coldplay"),
    ("In My Place", "Coldplay"),
    ("Numb", "Linkin Park"),
    ("In the End", "Linkin Park"),
    ("New Divide", "Linkin Park"),
    ("What I've Done", "Linkin Park"),
    ("Crawling", "Linkin Park"),
    ("Faint", "Linkin Park"),
    ("Breaking the Habit", "Linkin Park"),
    ("One More Light", "Linkin Park"),
    ("Burn It Down", "Linkin Park"),
    ("Creep", "Radiohead"),
    ("No Surprises", "Radiohead"),
    ("Karma Police", "Radiohead"),
    ("High and Dry", "Radiohead"),
    ("Back to Black", "Amy Winehouse"),
    ("Rehab", "Amy Winehouse"),
    ("Valerie", "Amy Winehouse"),
    ("Love Is A Losing Game", "Amy Winehouse"),
    ("Summertime Sadness", "Lana Del Rey"),
    ("Young and Beautiful", "Lana Del Rey"),
    ("Born to Die", "Lana Del Rey"),
    ("Video Games", "Lana Del Rey"),
    ("Blue Jeans", "Lana Del Rey"),
    ("Dark Paradise", "Lana Del Rey"),
    ("Ride", "Lana Del Rey"),
    ("Halo", "Beyonce"),
    ("Single Ladies", "Beyonce"),
    ("Crazy in Love", "Beyonce"),
    ("If I Were a Boy", "Beyonce"),
    ("Run the World", "Beyonce"),
    ("Poker Face", "Lady Gaga"),
    ("Bad Romance", "Lady Gaga"),
    ("Born This Way", "Lady Gaga"),
    ("Shallow", "Lady Gaga"),
    ("Paparazzi", "Lady Gaga"),
    ("Just Dance", "Lady Gaga"),
    ("Alejandro", "Lady Gaga"),
    ("Telephone", "Lady Gaga"),
    ("Roar", "Katy Perry"),
    ("Firework", "Katy Perry"),
    ("Dark Horse", "Katy Perry"),
    ("Teenage Dream", "Katy Perry"),
    ("Last Friday Night", "Katy Perry"),
    ("California Gurls", "Katy Perry"),
    ("I Kissed a Girl", "Katy Perry"),
    ("Hot N Cold", "Katy Perry"),
    ("Never Really Over", "Katy Perry"),
    ("Rude", "MAGIC!"),
    ("Cheap Thrills", "Sia"),
    ("Chandelier", "Sia"),
    ("Elastic Heart", "Sia"),
    ("Unstoppable", "Sia"),
    ("Titanium", "Sia"),
    ("Alive", "Sia"),
    ("Snowman", "Sia"),
    ("Stay With Me", "Sam Smith"),
    ("I'm Not the Only One", "Sam Smith"),
    ("Too Good at Goodbyes", "Sam Smith"),
    ("Writing's on the Wall", "Sam Smith"),
    ("Diamonds", "Sam Smith"),
    ("Dancing with a Stranger", "Sam Smith"),
    ("Unholy", "Sam Smith"),
    ("All of Me", "John Legend"),
    ("Ordinary People", "John Legend"),
    ("Love Me Now", "John Legend"),
    ("Tonight", "John Legend"),
    ("Just the Way You Are", "Bruno Mars"),
    ("Grenade", "Bruno Mars"),
    ("Locked Out of Heaven", "Bruno Mars"),
    ("When I Was Your Man", "Bruno Mars"),
    ("24K Magic", "Bruno Mars"),
    ("That's What I Like", "Bruno Mars"),
    ("Marry You", "Bruno Mars"),
    ("Talking to the Moon", "Bruno Mars"),
    ("Finesse", "Bruno Mars"),
    ("Leave The Door Open", "Bruno Mars"),

    # ==================== 抖音 2024-2025 热歌补充 ====================
    ("我知道", "BY2"),
    ("不要慌太阳下山有月光", "GooGoo"),
    ("小城夏天", "LBI利比"),
    ("壁上观", "一棵小葱"),
    ("化风行万里", "云朵"),
    ("我的楼兰", "云朵"),
    ("无名的人", "毛不易"),
    ("天地龙鳞", "王力宏"),
    ("若月亮没来", "王宇宙Leto"),
    ("如果可以", "韦礼安"),
    ("哪里都是你", "队长"),
    ("听闻远方有你", "刘艺雯"),
    ("人间半途", "刘阳阳"),
    ("转身即心痛", "吉星出租"),
    ("暮色回响", "张韶涵"),
    ("野花做了场玫瑰花的梦", "杨友友"),
    ("凄美地", "郭顶"),
    ("离别开出花", "就是南方凯"),
    ("可能", "程响"),
    ("诺言", "郭有才"),
    ("我记得", "赵雷"),
    ("瞬", "郑润泽"),
    ("青花", "周传雄"),
    ("虚拟", "陈粒"),
    ("人间烟火", "程响"),
    ("苹果香", "黑大婶"),
    ("指纹", "杜宣达"),
    ("寂寞烟火", "蓝心羽"),
    ("我期待的不是雪", "张妙格"),
    ("悬溺", "葛东琪"),
    ("Letting Go", "蔡健雅"),
    ("Always Online", "林俊杰"),
    ("桃花诺", "G.E.M.邓紫棋"),
    ("手心里的温柔", "刀郎"),
    ("西海情歌", "刀郎"),
    ("奢香夫人", "凤凰传奇"),
    ("喜欢你", "G.E.M.邓紫棋"),

    # ==================== 经典摇滚/流行英文歌补充 ====================
    ("Rocket Man", "Elton John"),
    ("Tiny Dancer", "Elton John"),
    ("Your Song", "Elton John"),
    ("Goodbye Yellow Brick Road", "Elton John"),
    ("Desperado", "Eagles"),
    ("Take It to the Limit", "Eagles"),
    ("Comfortably Numb", "Pink Floyd"),
    ("Wish You Were Here", "Pink Floyd"),
    ("Another Brick in the Wall", "Pink Floyd"),
    ("The Boxer", "Simon & Garfunkel"),
    ("Bridge Over Troubled Water", "Simon & Garfunkel"),
    ("Mrs. Robinson", "Simon & Garfunkel"),
    ("Radio Ga Ga", "Queen"),
    ("Under Pressure", "Queen"),
    ("Dancing Queen", "ABBA"),
    ("Mamma Mia", "ABBA"),
    ("Super Trouper", "ABBA"),
    ("Space Oddity", "David Bowie"),
    ("Heroes", "David Bowie"),
    ("Piano Man", "Billy Joel"),
    ("We Didn't Start the Fire", "Billy Joel"),
    ("Born to Run", "Bruce Springsteen"),
    ("Dancing in the Dark", "Bruce Springsteen"),
    ("Thunder Road", "Bruce Springsteen"),
    ("Purple Rain", "Prince"),
    ("Don't Stop Believin'", "Journey"),
    ("With or Without You", "U2"),
    ("One", "U2"),
    ("New Year's Day", "U2"),
    ("Livin' on a Prayer", "Bon Jovi"),
    ("Losing My Religion", "R.E.M."),
    ("Man on the Moon", "R.E.M."),
    ("Every Breath You Take", "The Police"),
    ("Take On Me", "A-ha"),
    ("Like a Prayer", "Madonna"),
    ("Pour Some Sugar On Me", "Def Leppard"),
    ("Hungry Like the Wolf", "Duran Duran"),
    ("When Doves Cry", "Prince"),
    ("I Can't Go for That", "Hall & Oates"),
    ("Like a Virgin", "Madonna"),
    ("You Shook Me All Night Long", "AC/DC"),
    ("How Will I Know", "Whitney Houston"),
    ("Walk Like an Egyptian", "The Bangles"),
    ("Jump", "Van Halen"),
    ("Need You Tonight", "INXS"),
    ("Here I Go Again", "Whitesnake"),
    ("Come On Eileen", "Dexy's Midnight Runners"),
    ("Time After Time", "Cyndi Lauper"),
    ("Jessie's Girl", "Rick Springfield"),
    ("Just Like Heaven", "The Cure"),
    ("Girls Just Want to Have Fun", "Cyndi Lauper"),
    ("Invisible Touch", "Genesis"),
    ("Sledgehammer", "Peter Gabriel"),
    ("Burning Down the House", "Talking Heads"),
    ("Addicted to Love", "Robert Palmer"),
    ("Everybody Wants to Rule the World", "Tears for Fears"),
    ("Total Eclipse of the Heart", "Bonnie Tyler"),
    ("Edge of Seventeen", "Stevie Nicks"),
    ("I'm Still Standing", "Elton John"),
    ("The Boys of Summer", "Don Henley"),
    ("Love Is a Battlefield", "Pat Benatar"),
    ("Let's Go Crazy", "Prince"),
    ("Any Way You Want It", "Journey"),

    # ==================== 更多国际经典 ====================
    ("Rhiannon", "Fleetwood Mac"),
    ("Gypsy", "Fleetwood Mac"),
    ("The Chain", "Fleetwood Mac"),
    ("Seven Wonders", "Fleetwood Mac"),
    ("Go Your Own Way", "Fleetwood Mac"),
    ("Landslide", "Fleetwood Mac"),
    ("Dreams", "Fleetwood Mac"),
    ("Don't Stop", "Fleetwood Mac"),
    ("Little Lies", "Fleetwood Mac"),
    ("Everywhere", "Fleetwood Mac"),
    ("Free Fallin'", "Tom Petty"),
    ("American Girl", "Tom Petty"),
    ("I Won't Back Down", "Tom Petty"),
    ("Learning to Fly", "Tom Petty"),
    ("Heart of Gold", "Neil Young"),
    ("Rockin' in the Free World", "Neil Young"),
    ("Old Man", "Neil Young"),
    ("The Joker", "Steve Miller Band"),
    ("Fly Like an Eagle", "Steve Miller Band"),
    ("Abracadabra", "Steve Miller Band"),
    ("More Than a Feeling", "Boston"),
    ("Peace of Mind", "Boston"),
    ("Carry on Wayward Son", "Kansas"),
    ("Dust in the Wind", "Kansas"),
    ("Dream On", "Aerosmith"),
    ("Walk This Way", "Aerosmith"),
    ("I Don't Want to Miss a Thing", "Aerosmith"),
    ("Crazy", "Aerosmith"),
    ("Sweet Emotion", "Aerosmith"),
    ("Barracuda", "Heart"),
    ("Alone", "Heart"),
    ("These Dreams", "Heart"),
    ("Magic Man", "Heart"),
    ("Black Dog", "Led Zeppelin"),
    ("Whole Lotta Love", "Led Zeppelin"),
    ("Kashmir", "Led Zeppelin"),
    ("Immigrant Song", "Led Zeppelin"),
    ("Ramble On", "Led Zeppelin"),
    ("Dazed and Confused", "Led Zeppelin"),
    ("Rock and Roll", "Led Zeppelin"),
    ("You Really Got Me", "The Kinks"),
    ("Lola", "The Kinks"),
    ("Sunny Afternoon", "The Kinks"),
    ("Waterloo Sunset", "The Kinks"),
    ("All Day and All of the Night", "The Kinks"),
    ("Brown Sugar", "The Rolling Stones"),
    ("Paint It Black", "The Rolling Stones"),
    ("Sympathy for the Devil", "The Rolling Stones"),
    ("Gimme Shelter", "The Rolling Stones"),
    ("Start Me Up", "The Rolling Stones"),
    ("Angie", "The Rolling Stones"),
    ("Miss You", "The Rolling Stones"),
    ("Satisfaction", "The Rolling Stones"),
    ("Jumpin' Jack Flash", "The Rolling Stones"),
    ("Ruby Tuesday", "The Rolling Stones"),
    ("Wild Horses", "The Rolling Stones"),
    ("Beast of Burden", "The Rolling Stones"),
    ("Layla", "Eric Clapton"),
    ("Tears in Heaven", "Eric Clapton"),
    ("Wonderful Tonight", "Eric Clapton"),
    ("Cocaine", "Eric Clapton"),
    ("I Shot the Sheriff", "Eric Clapton"),
    ("Sunshine of Your Love", "Cream"),
    ("White Room", "Cream"),
    ("Crossroads", "Cream"),
    ("Black Magic Woman", "Santana"),
    ("Smooth", "Santana"),
    ("Oye Como Va", "Santana"),
    ("Evil Ways", "Santana"),
    ("Europa", "Santana"),
    ("Samba Pa Ti", "Santana"),
    ("The Winner Takes It All", "ABBA"),
    ("Fernando", "ABBA"),
    ("Chiquitita", "ABBA"),
    ("Waterloo", "ABBA"),
    ("SOS", "ABBA"),
    ("Knowing Me Knowing You", "ABBA"),
    ("Money Money Money", "ABBA"),
    ("Gimme Gimme Gimme", "ABBA"),
    ("Voulez-Vous", "ABBA"),
    ("I Have a Dream", "ABBA"),
    ("Lay All Your Love on Me", "ABBA"),
    ("Dancing in the Moonlight", "King Harvest"),
    ("Brandy", "Looking Glass"),
    ("Come and Get Your Love", "Redbone"),
    ("Spirit in the Sky", "Norman Greenbaum"),
    ("All Right Now", "Free"),
    ("Smoke on the Water", "Deep Purple"),
    ("Highway Star", "Deep Purple"),
    ("Paranoid", "Black Sabbath"),
    ("Iron Man", "Black Sabbath"),
    ("War Pigs", "Black Sabbath"),
    ("Crazy Train", "Ozzy Osbourne"),
    ("Mama I'm Coming Home", "Ozzy Osbourne"),
    ("Mr. Crowley", "Ozzy Osbourne"),
    ("Breaking the Law", "Judas Priest"),
    ("Living After Midnight", "Judas Priest"),
    ("Ace of Spades", "Motorhead"),
    ("Rock You Like a Hurricane", "Scorpions"),
    ("Wind of Change", "Scorpions"),
    ("Still Loving You", "Scorpions"),
    ("No One Like You", "Scorpions"),
    ("Send Me an Angel", "Scorpions"),
    ("The Final Countdown", "Europe"),
    ("Carrie", "Europe"),
    ("Is This Love", "Whitesnake"),
    ("Still of the Night", "Whitesnake"),
    ("18 and Life", "Skid Row"),
    ("I Remember You", "Skid Row"),
    ("Every Rose Has Its Thorn", "Poison"),
    ("Nothin' But a Good Time", "Poison"),
    ("Talk Dirty to Me", "Poison"),
    ("Cherry Pie", "Warrant"),
    ("Heaven", "Warrant"),
    ("To Be with You", "Mr. Big"),
    ("More Than Words", "Extreme"),
    ("Hole Hearted", "Extreme"),
    ("Love of a Lifetime", "FireHouse"),
    ("When I Look Into Your Eyes", "FireHouse"),
    ("High Enough", "Damn Yankees"),
    ("Sister Christian", "Night Ranger"),
    ("Don't Tell Me You Love Me", "Night Ranger"),
    ("The Flame", "Cheap Trick"),
    ("I Want You to Want Me", "Cheap Trick"),
    ("Surrender", "Cheap Trick"),
    ("Dream Police", "Cheap Trick"),
    ("Eye of the Tiger", "Survivor"),
    ("Burning Heart", "Survivor"),
    ("The Search Is Over", "Survivor"),
    ("Can't Fight This Feeling", "REO Speedwagon"),
    ("Keep on Loving You", "REO Speedwagon"),
    ("Take It on the Run", "REO Speedwagon"),
    ("Rosanna", "Toto"),
    ("Africa", "Toto"),
    ("Hold the Line", "Toto"),
    ("I'll Be Over You", "Toto"),
    ("Missing You", "John Waite"),
    ("When I See You Smile", "Bad English"),
    ("Heaven", "Bryan Adams"),
    ("Summer of 69", "Bryan Adams"),
    ("Run to You", "Bryan Adams"),
    ("Everything I Do", "Bryan Adams"),
    ("Please Forgive Me", "Bryan Adams"),
    ("Have You Ever Really Loved a Woman", "Bryan Adams"),
    ("All for Love", "Bryan Adams"),
    ("It's My Life", "Bon Jovi"),
    ("Wanted Dead or Alive", "Bon Jovi"),
    ("You Give Love a Bad Name", "Bon Jovi"),
    ("Bad Medicine", "Bon Jovi"),
    ("Always", "Bon Jovi"),
    ("Bed of Roses", "Bon Jovi"),
    ("I'll Be There for You", "Bon Jovi"),
    ("Blaze of Glory", "Bon Jovi"),

    # ==================== 中国风 / 古风 ====================
    ("琵琶行", "奇然"),
    ("锦鲤抄", "银临"),
    ("牵丝戏", "银临"),
    ("故梦", "双笙"),
    ("我的一个道姑朋友", "以冬"),
    ("山有木兮", "伦桑"),
    ("吹梦到西洲", "黄诗扶"),
    ("九万字", "黄诗扶"),
    ("春三月", "司南"),
    ("冬眠", "司南"),
    ("烟雨行舟", "伦桑"),
    ("典狱司", "音频怪物"),
    ("琴师", "音频怪物"),
    ("长安忆", "音频怪物"),
    ("醉梦仙霖", "董贞"),
    ("枕边童话", "傲七爷"),
    ("红尘客栈", "奇然"),
    ("归去来兮", "叶炫清"),
    ("知否知否", "胡夏"),
    ("不染", "简弘亦"),
    ("左手指月", "萨顶顶"),
    ("大鱼", "周深"),
    ("起风了", "周深"),
    ("青花瓷", "李玉刚"),
    ("刚好遇见你", "李玉刚"),
    ("新贵妃醉酒", "李玉刚"),
    ("清明上河图", "李玉刚"),
    ("逐梦令", "李玉刚"),
    ("镜花水月", "李玉刚"),
    ("天池", "李玉刚"),
    ("水墨丹青", "李玉刚"),
    ("雨花石", "李玉刚"),
    ("霸王别姬", "李玉刚"),
    ("女儿情", "李玉刚"),
    ("悟空", "戴荃"),
    ("老神仙", "戴荃"),
    ("哪吒", "戴荃"),
    ("江湖晚", "戴荃"),
    ("少年中国说", "张杰"),
    ("踏山河", "等什么君"),
    ("谪仙", "叶里"),
    ("虞兮叹", "平生不晚"),
    ("伯虎说", "唐伯虎"),
    ("大天蓬", "李袁杰"),
    ("离人愁", "李袁杰"),
    ("醉千年", "李袁杰"),
    ("讲真的", "李袁杰"),
    ("广寒宫", "丸子呦"),
    ("苏幕遮", "张晓棠"),
    ("关山酒", "小魂"),
    ("长生诀", "西瓜JUN"),
    ("红昭愿", "音阙诗听"),
    ("芒种", "音阙诗听"),
    ("惊蛰", "音阙诗听"),
    ("谷雨", "音阙诗听"),
    ("立秋", "音阙诗听"),
    ("霜降", "音阙诗听"),
    ("大雪", "音阙诗听"),
    ("小寒", "音阙诗听"),
    ("夜宴风波", "音阙诗听"),
    ("洛阳怀", "李常超"),
    ("盗将行", "李常超"),
    ("与君同醉", "李常超"),
    ("天地难容", "W.K."),
    ("眉间雪", "HITA"),
    ("昔言", "HITA"),
    ("好梦如旧", "HITA"),
    ("明月天涯", "萧忆情"),
    ("拜无忧", "萧忆情"),
    ("倾尽天下", "河图"),
    ("第三十八年夏至", "河图"),
    ("风起天阑", "河图"),
    ("凤凰劫", "河图"),
    ("如花", "河图"),
    ("隐", "河图"),
    ("白衣", "河图"),
    ("阳关调", "河图"),
    ("为龙", "河图"),
    ("金陵秦淮夜", "河图"),
    ("华胥引", "河图"),
    ("伶仃谣", "河图"),
    ("寸缕", "河图"),
    ("永定四十年", "河图"),
    ("陌上花开", "河图"),
    ("寒衣调", "河图"),
    ("烬", "河图"),
    ("雨碎江南", "河图"),
    ("长安李白", "河图"),
    ("拉萨乱雪", "河图"),
    ("空山", "河图"),
    ("千秋罪", "河图"),
    ("山海侧", "银临"),
    ("腐草为萤", "银临"),
    ("是风动", "银临"),
    ("流光记", "银临"),
    ("妙笔浮生", "银临"),
    ("有一封信", "银临"),
    ("琉璃", "银临"),
    ("不老梦", "银临"),
    ("裁梦为魂", "银临"),
    ("浮生辞", "银临"),
    ("枕上雪", "银临"),

    # ==================== 更多周深 / 张碧晨 / 热门歌手 ====================
    ("和光同尘", "周深"),
    ("光亮", "周深"),
    ("若梦", "周深"),
    ("人是_", "周深"),
    ("灯火里的中国", "周深"),
    ("我的答案", "周深"),
    ("悬崖之上", "周深"),
    ("触不可及", "周深"),
    ("Rubia", "周深"),
    ("借给我一盒火柴", "周深"),
    ("年轮", "张碧晨"),
    ("下一秒", "张碧晨"),
    ("开往早晨的午夜", "张碧晨"),
    ("一吻之间", "张碧晨"),
    ("只要平凡", "张碧晨"),
    ("光的方向", "张碧晨"),
    ("笼", "张碧晨"),
    ("孤勇者", "张碧晨"),
    ("胡桃夹子", "张碧晨"),
    ("白芍花开", "张碧晨"),
    ("染", "张碧晨"),
    ("如故", "张碧晨"),
    ("听雪", "张碧晨"),
    ("水从天上来", "张碧晨"),
    ("炽热的你", "张碧晨"),
    ("念念不忘", "张碧晨"),
    ("字字句句", "张碧晨"),
    ("无名的人", "张碧晨"),

    # ==================== 更多唱作人 ====================
    ("奇妙能力歌", "陈粒"),
    ("历历万乡", "陈粒"),
    ("走马", "陈粒"),
    ("小半", "陈粒"),
    ("易燃易爆炸", "陈粒"),
    ("光", "陈粒"),
    ("如也", "陈粒"),
    ("性空山", "陈粒"),
    ("种种", "陈粒"),
    ("芳草地", "陈粒"),
    ("远辰", "陈粒"),
    ("戏台", "陈粒"),
    ("不灭", "陈粒"),
    ("当我在这里", "陈粒"),
    ("花开在眼前", "陈粒"),
    ("南山南", "马頔"),
    ("傲寒", "马頔"),
    ("皆非", "马頔"),
    ("大雁", "马頔"),
    ("孤鸟的歌", "马頔"),
    ("切尔西旅馆有没有8310", "马頔"),
    ("时间里的", "马頔"),
    ("海咪咪小姐", "马頔"),
    ("棺木", "马頔"),
    ("一个人的北京", "好妹妹乐队"),
    ("你飞到城市另一边", "好妹妹乐队"),
    ("我说今晚月光那么美", "好妹妹乐队"),
    ("往事只能回味", "好妹妹乐队"),
    ("青城山下白素贞", "好妹妹乐队"),
    ("相思赋予谁", "好妹妹乐队"),
    ("送你一朵山茶花", "好妹妹乐队"),
    ("西窗的雨", "好妹妹乐队"),
    ("晚风", "好妹妹乐队"),
    ("松林的低语", "好妹妹乐队"),
    ("无常", "好妹妹乐队"),
    ("流浪者之歌", "好妹妹乐队"),
    ("时光小酒馆", "好妹妹乐队"),
    ("不说再见", "好妹妹乐队"),
    ("普通人", "好妹妹乐队"),
    ("给自己的信", "好妹妹乐队"),

    # ==================== 2024-2025 国际热歌补充 ====================
    ("We Can't Be Friends", "Ariana Grande"),
    ("Yes And", "Ariana Grande"),
    ("The Boy Is Mine", "Ariana Grande"),
    ("Eternal Sunshine", "Ariana Grande"),
    ("Training Season", "Dua Lipa"),
    ("Illusion", "Dua Lipa"),
    ("These Walls", "Dua Lipa"),
    ("Dance the Night", "Dua Lipa"),
    ("I Can Do It With a Broken Heart", "Taylor Swift"),
    ("So Long London", "Taylor Swift"),
    ("But Daddy I Love Him", "Taylor Swift"),
    ("Florida", "Taylor Swift"),
    ("Guilty as Sin", "Taylor Swift"),
    ("Who's Afraid of Little Old Me", "Taylor Swift"),
    ("I Can Fix Him", "Taylor Swift"),
    ("loml", "Taylor Swift"),
    ("The Smallest Man Who Ever Lived", "Taylor Swift"),
    ("Clara Bow", "Taylor Swift"),
    ("The Alchemy", "Taylor Swift"),
    ("Snooze", "SZA"),
    ("Kill Bill", "SZA"),
    ("Nobody Gets Me", "SZA"),
    ("Shirt", "SZA"),
    ("Blind", "SZA"),
    ("Low", "SZA"),
    ("Gone Girl", "SZA"),
    ("Special", "SZA"),
    ("Paint the Town Red", "Doja Cat"),
    ("Agora Hills", "Doja Cat"),
    ("Demons", "Doja Cat"),
    ("Attention", "Doja Cat"),
    ("Balut", "Doja Cat"),
    ("Gun", "Doja Cat"),
    ("Wet Vagina", "Doja Cat"),
    ("Fuck the Girls", "Doja Cat"),
    ("Ouchies", "Doja Cat"),
    ("Lose Control", "Teddy Swims"),
    ("The Door", "Teddy Swims"),
    ("Hammer to the Heart", "Teddy Swims"),
    ("Bad Dreams", "Teddy Swims"),
    ("A Bar Song", "Shaboozey"),
    ("Beautiful Things", "Benson Boone"),
    ("Slow It Down", "Benson Boone"),
    ("Cry", "Benson Boone"),
    ("Ghost Town", "Benson Boone"),
    ("In the Stars", "Benson Boone"),
    ("I Had Some Help", "Post Malone"),
    ("Sunflower", "Post Malone"),
    ("Circles", "Post Malone"),
    ("Better Now", "Post Malone"),
    ("Rockstar", "Post Malone"),
    ("Congratulations", "Post Malone"),
    ("White Iverson", "Post Malone"),
    ("Chemical", "Post Malone"),
    ("Mourning", "Post Malone"),
    ("Overdrive", "Post Malone"),
    ("Enough Is Enough", "Post Malone"),
    ("Too Sweet", "Hozier"),
    ("Take Me to Church", "Hozier"),
    ("Cherry Wine", "Hozier"),
    ("Someone New", "Hozier"),
    ("Almost", "Hozier"),
    ("Work Song", "Hozier"),
    ("Like Real People Do", "Hozier"),
    ("From Eden", "Hozier"),
    ("Eat Your Young", "Hozier"),
    ("Francesca", "Hozier"),
    ("Stick Season", "Noah Kahan"),
    ("Dial Drunk", "Noah Kahan"),
    ("Northern Attitude", "Noah Kahan"),
    ("All My Love", "Noah Kahan"),
    ("False Confidence", "Noah Kahan"),
    ("Greedy", "Tate McRae"),
    ("Exes", "Tate McRae"),
    ("Grave", "Tate McRae"),
    ("Run for the Hills", "Tate McRae"),
    ("She's All I Wanna Be", "Tate McRae"),
    ("You Broke Me First", "Tate McRae"),
    ("What Would You Do", "Tate McRae"),
    ("Don't Come Back", "Tate McRae"),
    ("Hurt My Feelings", "Tate McRae"),
    ("Messier", "Tate McRae"),
    ("Feather", "Sabrina Carpenter"),
    ("Nonsense", "Sabrina Carpenter"),
    ("Espresso", "Sabrina Carpenter"),
    ("Please Please Please", "Sabrina Carpenter"),
    ("Taste", "Sabrina Carpenter"),
    ("Bed Chem", "Sabrina Carpenter"),
    ("Juno", "Sabrina Carpenter"),
    ("Good Luck Babe", "Chappell Roan"),
    ("Hot to Go", "Chappell Roan"),
    ("Red Wine Supernova", "Chappell Roan"),
    ("Pink Pony Club", "Chappell Roan"),
    ("Casual", "Chappell Roan"),
    ("Femininomenon", "Chappell Roan"),
    ("My Kink Is Karma", "Chappell Roan"),
    ("Birds of a Feather", "Billie Eilish"),
    ("Lunch", "Billie Eilish"),
    ("Chihiro", "Billie Eilish"),
    ("Wildflower", "Billie Eilish"),
    ("The Greatest", "Billie Eilish"),
    ("L'Amour de Ma Vie", "Billie Eilish"),
    ("Bad Guy", "Billie Eilish"),
    ("Happier Than Ever", "Billie Eilish"),
    ("Everything I Wanted", "Billie Eilish"),
    ("Ocean Eyes", "Billie Eilish"),
    ("Therefore I Am", "Billie Eilish"),
    ("Lovely", "Billie Eilish"),
    ("What Was I Made For", "Billie Eilish"),
    ("Die with a Smile", "Lady Gaga"),
    ("Disease", "Lady Gaga"),
    ("Abracadabra", "Lady Gaga"),
    ("Fortnight", "Taylor Swift"),
    ("Down Bad", "Taylor Swift"),
    ("My Boy Only Breaks His Favorite Toys", "Taylor Swift"),
    ("Fresh Out the Slammer", "Taylor Swift"),
    ("imgonnagetyouback", "Taylor Swift"),
    ("The Prophecy", "Taylor Swift"),
    ("Peter", "Taylor Swift"),
    ("The Bolter", "Taylor Swift"),
    ("Robin", "Taylor Swift"),
    ("The Manuscript", "Taylor Swift"),
    ("Water", "Tyla"),
    ("Truth or Dare", "Tyla"),
    ("Art", "Tyla"),
    ("Jump", "Tyla"),
    ("Push 2 Start", "Tyla"),
    ("Saturn", "SZA"),
    ("DTM", "SZA"),
    ("Diamond Boy", "SZA"),
    ("Far", "SZA"),
    ("Love Galore", "SZA"),
    ("The Weekend", "SZA"),
    ("Broken Clocks", "SZA"),
    ("Drew Barrymore", "SZA"),
    ("Normal Girl", "SZA"),
    ("Supermodel", "SZA"),
    ("Good Days", "SZA"),
    ("I Hate U", "SZA"),
    ("Seek & Destroy", "SZA"),
    ("Luther", "Kendrick Lamar"),
    ("Not Like Us", "Kendrick Lamar"),
    ("Euphoria", "Kendrick Lamar"),
    ("Meet the Grahams", "Kendrick Lamar"),
    ("HUMBLE", "Kendrick Lamar"),
    ("DNA", "Kendrick Lamar"),
    ("Alright", "Kendrick Lamar"),
    ("King Kunta", "Kendrick Lamar"),
    ("Swimming Pools", "Kendrick Lamar"),
    ("Bitch Don't Kill My Vibe", "Kendrick Lamar"),
    ("Money Trees", "Kendrick Lamar"),
    ("Poetic Justice", "Kendrick Lamar"),
    ("Backseat Freestyle", "Kendrick Lamar"),
    ("m.A.A.d city", "Kendrick Lamar"),
    ("PRIDE", "Kendrick Lamar"),
    ("LOVE", "Kendrick Lamar"),
    ("All the Stars", "Kendrick Lamar"),
    ("Family Ties", "Kendrick Lamar"),
    ("The Heart Part 5", "Kendrick Lamar"),
    ("Count Me Out", "Kendrick Lamar"),
    ("N95", "Kendrick Lamar"),
    ("Rich Spirit", "Kendrick Lamar"),
    ("Die Hard", "Kendrick Lamar"),
    ("Like That", "Future"),
    ("Type Shit", "Future"),
    ("We Don't Trust You", "Future"),
    ("Mask Off", "Future"),
    ("Life Is Good", "Future"),
    ("Low Life", "Future"),
    ("March Madness", "Future"),
    ("Codeine Crazy", "Future"),
    ("Stick Talk", "Future"),
    ("Fuck Up Some Commas", "Future"),
    ("Where Ya At", "Future"),
    ("Jumpman", "Future"),
]

# 额外歌曲变体（在基础歌曲上增加版本后缀以扩充数量）
SONG_VARIATIONS = [
    ("{name} (Live版)", "{artist}"),
    ("{name} (Remix版)", "{artist}"),
    ("{name} (Acoustic版)", "{artist}"),
    ("{name} (伴奏版)", "{artist}"),
    ("{name} (DJ版)", "{artist}"),
    ("{name} (Cover版)", "{artist}"),
]


def get_connection():
    """获取 MySQL 数据库连接"""
    return pymysql.connect(**MYSQL_CONFIG)


def get_minio_client():
    """获取 MinIO 客户端"""
    return Minio(
        MINIO_CONFIG["endpoint"],
        access_key=MINIO_CONFIG["access_key"],
        secret_key=MINIO_CONFIG["secret_key"],
        secure=MINIO_CONFIG["secure"],
    )


def pick_source_audio():
    """从本地 song 目录随机选择一个音频文件"""
    if not os.path.exists(LOCAL_SONG_DIR):
        print(f"错误：本地音频目录不存在: {LOCAL_SONG_DIR}")
        sys.exit(1)
    files = [
        f for f in os.listdir(LOCAL_SONG_DIR)
        if f.lower().endswith(('.mp3', '.wav', '.flac', '.m4a', '.ogg', '.wma'))
        if not f.startswith('.')
    ]
    if not files:
        print(f"错误：目录中没有音频文件: {LOCAL_SONG_DIR}")
        sys.exit(1)
    chosen = random.choice(files)
    return os.path.join(LOCAL_SONG_DIR, chosen), chosen


def ensure_minio_bucket(client):
    """确保 MinIO bucket 存在"""
    bucket = MINIO_CONFIG["bucket_name"]
    if not client.bucket_exists(bucket):
        client.make_bucket(bucket)
        print(f"已创建 bucket: {bucket}")
    return bucket


def upload_to_minio(client, bucket, local_path, object_name):
    """上传文件到 MinIO"""
    try:
        client.stat_object(bucket, object_name)
        print(f"  已存在，跳过: {object_name}")
        return True
    except S3Error:
        pass
    client.fput_object(bucket, object_name, local_path)
    return True


def copy_in_minio(client, bucket, source_object, target_object):
    """在 MinIO 内复制对象"""
    try:
        client.stat_object(bucket, target_object)
        return True
    except S3Error:
        pass
    # MinIO Python SDK copy: use copy_object
    from minio.commonconfig import CopySource
    client.copy_object(
        bucket, target_object,
        CopySource(bucket, source_object)
    )
    return True


def build_song_list():
    """构建完整的歌曲列表（基础 + 变体）"""
    all_songs = list(SONGS)

    # 为部分歌曲生成变体以扩充数据量
    base_count = len(SONGS)
    variations_needed = max(0, TARGET_COUNT - base_count)
    if variations_needed > 0:
        # 随机选择歌曲添加变体后缀
        random.seed(42)  # 固定种子保证可重复
        for i in range(variations_needed):
            name, artist = random.choice(SONGS)
            variant_name_pattern, variant_artist_pattern = random.choice(SONG_VARIATIONS)
            new_name = variant_name_pattern.replace("{name}", name)
            # 限制变体名长度（数据库 name 字段 varchar(45) 限制 45 字符）
            if len(new_name) > 45:
                new_name = name + " (Live)"
            all_songs.append((new_name, artist))

    random.shuffle(all_songs)
    return all_songs[:TARGET_COUNT]


def create_singers(conn, songs):
    """批量创建歌手记录，返回 {歌手名: singer_id} 映射"""
    # 提取所有唯一歌手
    unique_singers = list(set(artist for _, artist in songs))
    print(f"共有 {len(unique_singers)} 个唯一歌手")

    singer_map = {}
    with conn.cursor() as cursor:
        # 查询已存在的歌手
        for singer_name in unique_singers:
            cursor.execute("SELECT id FROM singer WHERE name = %s", (singer_name,))
            row = cursor.fetchone()
            if row:
                singer_map[singer_name] = row[0]
            else:
                # 插入新歌手
                cursor.execute(
                    """INSERT INTO singer (name, sex, pic, birth, location, introduction)
                    VALUES (%s, %s, %s, %s, %s, %s)""",
                    (
                        singer_name,
                        random.choice([0, 1]),
                        "/img/singerPic/default.jpg",
                        datetime.date(
                            random.randint(1960, 2005),
                            random.randint(1, 12),
                            random.randint(1, 28)
                        ),
                        random.choice(["北京", "上海", "广州", "香港", "台北", "成都", "深圳", "首尔", "纽约", "伦敦"]),
                        f"{singer_name}是一位优秀的音乐人。"
                    )
                )
                singer_map[singer_name] = cursor.lastrowid

    conn.commit()
    print(f"歌手记录已就绪: {len(singer_map)} 个")
    return singer_map


def create_songs(conn, songs, singer_map, audio_url):
    """批量创建歌曲记录"""
    # 预先取一些图片路径用于随机分配
    with conn.cursor() as cursor:
        cursor.execute("SELECT pic FROM song WHERE pic IS NOT NULL AND pic != '' LIMIT 50")
        existing_pics = [row[0] for row in cursor.fetchall()]
    if not existing_pics:
        existing_pics = ["/img/songPic/default.jpg"]

    batch_size = 100
    total = len(songs)
    inserted = 0

    for i in range(0, total, batch_size):
        batch = songs[i:i + batch_size]
        with conn.cursor() as cursor:
            for name, artist in batch:
                singer_id = singer_map.get(artist, 1)
                pic = random.choice(existing_pics)
                intro = f"{artist}演唱的《{name}》"
                create_time = datetime.datetime(
                    random.randint(2010, 2025),
                    random.randint(1, 12),
                    random.randint(1, 28),
                    random.randint(0, 23),
                    random.randint(0, 59),
                    random.randint(0, 59)
                )
                update_time = create_time + datetime.timedelta(days=random.randint(1, 365))

                cursor.execute(
                    """INSERT INTO song (singer_id, name, introduction, create_time, update_time, pic, lyric, url)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                    (singer_id, name, intro, create_time, update_time, pic, "", audio_url)
                )
                inserted += 1
        conn.commit()
        print(f"  进度: {min(i + batch_size, total)}/{total}")

    return inserted


def main():
    print("=" * 60)
    print("音乐数据扩充工具")
    print("=" * 60)

    # 1. 构建歌曲列表
    print("\n[1/5] 构建歌曲列表...")
    songs = build_song_list()
    print(f"  共 {len(songs)} 首歌曲待生成")

    # 2. 选择源音频
    print("\n[2/5] 选择源音频文件...")
    source_path, source_filename = pick_source_audio()
    print(f"  选择: {source_filename}")
    print(f"  路径: {source_path}")

    # 3. 连接 MinIO 并上传
    print("\n[3/5] 连接 MinIO...")
    try:
        minio_client = get_minio_client()
        bucket = ensure_minio_bucket(minio_client)
        print(f"  MinIO 连接成功，bucket: {bucket}")
    except Exception as e:
        print(f"  MinIO 连接失败: {e}")
        print("  请确保 MinIO 服务已启动 (端口 9005)")
        sys.exit(1)

    # 上传源音频
    object_prefix = f"song/{uuid.uuid4().hex[:8]}"
    source_ext = os.path.splitext(source_filename)[1]
    source_object = f"{object_prefix}_source{source_ext}"
    print(f"  上传源音频: {source_path} -> {source_object}")
    upload_to_minio(minio_client, bucket, source_path, source_object)

    # 音频 URL（数据库存储路径）
    if COPY_AUDIO_IN_MINIO:
        audio_url = f"/song/{uuid.uuid4().hex}{source_ext}"
    else:
        audio_url = f"/{source_object}"

    # 4. 连接 MySQL
    print("\n[4/5] 连接 MySQL...")
    try:
        conn = get_connection()
        print(f"  MySQL 连接成功: {MYSQL_CONFIG['host']}:{MYSQL_CONFIG['port']}/{MYSQL_CONFIG['database']}")
    except Exception as e:
        print(f"  MySQL 连接失败: {e}")
        print("  请确保 MySQL 服务已启动 (端口 3306)")
        sys.exit(1)

    try:
        # 清空旧测试数据（可选）
        print("\n  注意：将保留现有数据，仅追加新记录")
        print(f"  当前 song 表记录数: ", end="")
        with conn.cursor() as c:
            c.execute("SELECT COUNT(*) FROM song")
            existing = c.fetchone()[0]
        print(f"{existing}")

        # 创建歌手
        print(f"\n  创建歌手记录...")
        singer_map = create_singers(conn, songs)

        # 创建歌曲
        print(f"\n  创建歌曲记录...")
        inserted = create_songs(conn, songs, singer_map, audio_url)
        print(f"\n  成功插入 {inserted} 条歌曲记录！")

        # 验证
        with conn.cursor() as c:
            c.execute("SELECT COUNT(*) FROM song")
            total_after = c.fetchone()[0]
        print(f"  当前 song 表总记录数: {total_after}")

    finally:
        conn.close()

    # 5. 完成
    print("\n[5/5] 完成！")
    print("=" * 60)
    print(f"  新增歌曲: {inserted} 条")
    print(f"  音频文件: {source_filename}")
    if COPY_AUDIO_IN_MINIO:
        print(f"  MinIO 对象: {inserted} 个独立副本")
    else:
        print(f"  MinIO 对象: 1 个（所有歌曲共用）")
    print("=" * 60)


if __name__ == "__main__":
    main()
